import os
import subprocess
import tempfile
from flask import Flask, request, send_file
from werkzeug.utils import secure_filename

app = Flask(__name__)

@app.route('/convert', methods=['POST'])
def convert_file():
    # 1. Validation
    if 'file' not in request.files:
        return {'error': 'No file part in the request'}, 400
    
    file = request.files['file']
    output_filename = request.form.get('output_filename')

    if file.filename == '':
        return {'error': 'No selected file'}, 400
    
    if not output_filename:
        return {'error': 'No output_filename provided'}, 400

    # Secure filenames to prevent path traversal
    input_filename = secure_filename(file.filename)
    output_filename = secure_filename(output_filename) 

    # 2. Processing
    with tempfile.TemporaryDirectory() as temp_dir:
        input_path = os.path.join(temp_dir, input_filename)
        output_path = os.path.join(temp_dir, output_filename)

        # Save the uploaded file
        file.save(input_path)

        # Construct the pandoc command
        cmd = [
            'pandoc',
            input_path,
            '-o', output_path,
            '--standalone'
        ]

        # Handle PDF Engine choice via Environment Variable
        if output_filename.endswith('.pdf'):
            # Defaults to 'xelatex' if set in Dockerfile, otherwise 'pdflatex'
            pdf_engine = os.environ.get('PDF_ENGINE', 'pdflatex')
            cmd.extend(['--pdf-engine', pdf_engine])

        try:
            # Run pandoc
            result = subprocess.run(
                cmd, 
                check=True, 
                capture_output=True, 
                text=True
            )
        except subprocess.CalledProcessError as e:
            return {
                'error': 'Conversion failed', 
                'stderr': e.stderr, 
                'stdout': e.stdout
            }, 500

        # 3. Response
        if not os.path.exists(output_path):
            return {'error': 'Output file was not generated by pandoc'}, 500

        try:
            return send_file(
                output_path, 
                as_attachment=True, 
                download_name=output_filename
            )
        except Exception as e:
            return {'error': f'Failed to send file: {str(e)}'}, 500

@app.route('/health', methods=['GET'])
def health():
    return {'status': 'ok', 'pandoc_version': subprocess.getoutput('pandoc --version').split('\n')[0]}

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000)